### ISSUE TITLE
AUC was not change when I change ratio

### ISSUE THREAD

**Issue by secondmany** [yage99/mkl#1]
Hi, 

I run your code with data download from TCGA. But, if I changed the ratio (known as a number of features after reduced by mrmr method) from 130 to 400, the AUC of classification model was not changed and if the ratio was less than 130, your code show error.

Help me to explain this issues. 

Thank you so much,

**Comment by yage99** [comment]
hi @secondmany There is a corresponding variable "variableveccell" in "mklclassify" function which sets features used in different kernels. If you changed the number of features, "variableveccell" needs to be changed either.
